export const ROUTES = {
  home: '/',
  destinations: '/destinations',
  destinationDetail: (slug) => `/destinations/${slug}`,
  packages: '/packages',
  packageDetail: (slug) => `/packages/${slug}`,
  experiences: '/experiences',
  experienceDetail: (slug) => `/experiences/${slug}`,
  travelGuide: '/travel-guide',
  travelGuidePost: (slug) => `/travel-guide/${slug}`,
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  account: '/account',
  myTrips: '/my-trips',
  favorites: '/favorites',
  bookingDates: (packageId) => `/booking/${packageId}/dates`,
  bookingCustomize: (packageId) => `/booking/${packageId}/customize`,
  bookingTravelers: (packageId) => `/booking/${packageId}/travelers`,
  bookingReview: (packageId) => `/booking/${packageId}/review`,
  bookingPayment: (packageId) => `/booking/${packageId}/payment`,
  bookingConfirmation: (bookingId) => `/booking/confirmation/${bookingId}`,
  support: '/support',
  contact: '/contact',
  faq: '/faq',
  about: '/about',
}
